/**
 * Tokens y estilos del panel Ops (.ops-* del ops.css web), claro/oscuro.
 * useOpsStyles() devuelve { s, op } ya resuelto sobre el tema actual;
 * conFuentes() inyecta Plus Jakarta por fontWeight (como OpTokens).
 */
import { StyleSheet } from 'react-native';
import { useTheme } from '../../theme/ThemeContext';
import { FUENTES } from '../../theme/tokens';

export const MONO = 'monospace';

const CLARO = {
  surface: '#f9f9ff',
  surfaceLowest: '#ffffff',
  surfaceLow: '#f0f3ff',
  surfaceContainer: '#e7eeff',
  surfaceHigh: '#dee8ff',
  surfaceHighest: '#d8e3fb',
  onSurface: '#111c2d',
  onVariant: '#3f4942',
  outline: '#6f7a72',
  outlineVariant: '#bec9c0',
  primary: '#005134',
  primaryContainer: '#0e6b47',
  onPrimary: '#ffffff',
  secondary: '#006d37',
  secondaryContainer: '#6bfe9c',
  onSecondaryContainer: '#00743a',
  tertiary: '#004393',
  tertiaryContainer: '#005ac0',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  shadowColor: '#0e6b47',
  shadowOpacity: 0.05,
  shadowLgOpacity: 0.08,
};

const OSCURO = {
  ...CLARO,
  surface: '#0f1310',
  surfaceLowest: '#171b17',
  surfaceLow: '#1d221d',
  surfaceContainer: '#232a23',
  surfaceHigh: '#2b332b',
  surfaceHighest: '#333c33',
  onSurface: '#e8eee9',
  onVariant: '#a7b0a6',
  outline: '#8a938a',
  outlineVariant: '#3a403a',
  shadowColor: '#000000',
  shadowOpacity: 0.4,
  shadowLgOpacity: 0.5,
};

const sombra = (op) => ({
  shadowColor: op.shadowColor,
  shadowOpacity: op.shadowOpacity,
  shadowRadius: 3,
  shadowOffset: { width: 0, height: 1 },
  elevation: 1,
});

const sombraLg = (op) => ({
  shadowColor: op.shadowColor,
  shadowOpacity: op.shadowLgOpacity,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 6 },
  elevation: 4,
});

function conFuentes(styles) {
  Object.keys(styles).forEach((k) => {
    const st = styles[k];
    if (!st || typeof st !== 'object' || Array.isArray(st)) return;
    if (st.fontWeight && !st.fontFamily) {
      const w = String(st.fontWeight);
      st.fontFamily =
        w === '800'
          ? FUENTES.textoExtra
          : w === '700'
            ? FUENTES.textoBold
            : w === '600'
              ? FUENTES.textoSemi
              : w === '500'
                ? FUENTES.textoMedio
                : FUENTES.texto;
    }
    if (!st.fontFamily && !st.includeFontPadding) st.fontFamily = FUENTES.texto;
  });
  return styles;
}

export function useOpsStyles() {
  const { tema } = useTheme();
  const op = tema === 'oscuro' ? OSCURO : CLARO;

  const s = conFuentes(
    StyleSheet.create({
      // — Shell / layout —
      shell: { flex: 1, backgroundColor: op.surface },
      contenido: {
        padding: 16,
        paddingBottom: 40,
        gap: 20,
        maxWidth: 1560,
        width: '100%',
        alignSelf: 'center',
      },
      header: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingHorizontal: 12,
        height: 60,
        backgroundColor: op.surfaceLowest,
        borderBottomWidth: 1,
        borderBottomColor: op.surfaceContainer,
      },
      headerSpacer: { flex: 1 },
      search: { flex: 1, maxWidth: 560, flexDirection: 'row', alignItems: 'center' },
      searchInput: {
        flex: 1,
        height: 40,
        paddingHorizontal: 38,
        borderRadius: 8,
        backgroundColor: op.surfaceLow,
        color: op.onSurface,
        fontSize: 14,
      },
      searchCaja: { flex: 1, maxWidth: 560, position: 'relative', justifyContent: 'center' },
      searchIcon: { position: 'absolute', left: 11, color: op.outline, zIndex: 2 },
      iconBtn: {
        width: 40,
        height: 40,
        borderRadius: 8,
        backgroundColor: op.surfaceLow,
        alignItems: 'center',
        justifyContent: 'center',
      },
      pingDot: {
        position: 'absolute',
        top: 7,
        right: 7,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: op.error,
        borderWidth: 2,
        borderColor: op.surfaceLowest,
      },
      profile: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 6 },
      profileMeta: { lineHeight: 1.2 },
      profileNombre: { fontSize: 12, fontWeight: '700', color: op.onSurface },
      profileRol: { fontSize: 12, color: op.onVariant },
      avatar: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: op.primaryContainer,
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '700',
        fontSize: 14,
        color: '#ffffff',
      },

      // — Drawer / sidebar —
      drawerOverlay: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(17,28,45,0.55)' },
      drawer: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        width: 288,
        backgroundColor: op.surfaceLowest,
        borderRightWidth: 1,
        borderRightColor: op.surfaceContainer,
        zIndex: 72,
        justifyContent: 'space-between',
        overflow: 'hidden',
      },
      brand: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        height: 60,
        paddingLeft: 22,
        borderBottomWidth: 1,
        borderBottomColor: op.surfaceLow,
      },
      brandImg: { width: 32, height: 32, borderRadius: 8 },
      brandName: { fontSize: 16, fontWeight: '700', color: op.primary, lineHeight: 17.6 },
      brandSub: { fontSize: 11, fontWeight: '700', letterSpacing: 0.9, color: op.onVariant },
      navLabel: {
        paddingTop: 14,
        paddingBottom: 6,
        paddingHorizontal: 28,
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.7,
        color: op.onVariant,
      },
      nav: { paddingHorizontal: 12, gap: 2 },
      navItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 9,
        paddingHorizontal: 14,
        borderRadius: 8,
        backgroundColor: 'transparent',
        width: '100%',
      },
      navItemActivo: {
        backgroundColor: op.primaryContainer,
        shadowColor: '#0e6b47',
        shadowOpacity: 0.25,
        shadowRadius: 3,
        shadowOffset: { width: 0, height: 1 },
        elevation: 2,
      },
      navItemIzq: { flexDirection: 'row', alignItems: 'center', gap: 12, minWidth: 0, flex: 1 },
      navItemTxt: { fontSize: 14, fontWeight: '600', color: op.onVariant },
      navItemTxtActivo: { fontSize: 14, fontWeight: '700', color: '#ffffff' },
      badge: {
        fontSize: 11,
        fontWeight: '700',
        paddingVertical: 2,
        paddingHorizontal: 8,
        borderRadius: 999,
        backgroundColor: op.secondaryContainer,
        color: op.onSecondaryContainer,
        overflow: 'hidden',
      },
      badgeCrit: { backgroundColor: op.errorContainer, color: op.onErrorContainer },
      dotLive: { width: 8, height: 8, borderRadius: 4, backgroundColor: op.secondary },
      sideFoot: {
        padding: 16,
        gap: 10,
        backgroundColor: op.surfaceLow,
        borderTopWidth: 1,
        borderTopColor: op.surfaceContainer,
      },
      sys: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: op.surfaceLowest,
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 12,
        fontSize: 11,
        fontWeight: '600',
        color: op.onVariant,
        ...sombra(op),
      },
      sysLive: { color: op.secondary, fontWeight: '700', fontSize: 11 },
      themeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 4,
        fontSize: 11,
        fontWeight: '600',
        color: op.onVariant,
      },
      themeBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: op.surfaceLowest,
        borderRadius: 8,
        paddingVertical: 6,
        paddingHorizontal: 10,
        fontSize: 11,
        fontWeight: '600',
        color: op.onVariant,
        ...sombra(op),
      },
      userbox: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 4 },
      userboxNombre: { fontSize: 12, fontWeight: '600', color: op.onSurface, flexShrink: 1 },
      userboxMail: { fontSize: 12, color: op.onVariant, flexShrink: 1 },

      // — Hero —
      hero: {
        backgroundColor: op.surfaceLowest,
        borderRadius: 12,
        padding: 20,
        gap: 12,
        ...sombra(op),
      },
      liveChip: {
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.55,
        color: op.primary,
        backgroundColor: op.surfaceContainer,
        borderRadius: 999,
        paddingVertical: 3,
        paddingHorizontal: 10,
        overflow: 'hidden',
        textTransform: 'uppercase',
      },
      sync: { fontSize: 12, color: op.onVariant },
      heroTitle: { fontSize: 24, lineHeight: 32, letterSpacing: -0.48, fontWeight: '700', marginTop: 6, marginBottom: 4, color: op.onSurface },
      heroP: { color: op.onVariant, fontSize: 14, lineHeight: 20 },
      actions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },

      // — Botones —
      btn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        borderRadius: 8,
        paddingVertical: 9,
        paddingHorizontal: 16,
        fontSize: 14,
        fontWeight: '600',
      },
      btnPrimary: {
        backgroundColor: op.primaryContainer,
        color: '#ffffff',
        shadowColor: '#0e6b47',
        shadowOpacity: 0.25,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
      },
      btnSoft: { backgroundColor: op.surfaceLow, color: op.onSurface },
      btnDanger: { backgroundColor: op.error, color: '#ffffff' },
      btnSm: { paddingVertical: 6, paddingHorizontal: 12, fontSize: 12 },
      btnDisabled: { opacity: 0.5 },
      btnTxt: { fontSize: 14, fontWeight: '600' },
      btnTxtSm: { fontSize: 12, fontWeight: '600' },

      // — KPIs —
      kpis: { flexDirection: 'row', flexWrap: 'wrap', gap: 14 },
      kpi: {
        backgroundColor: op.surfaceLowest,
        borderRadius: 12,
        padding: 16,
        gap: 4,
        flexGrow: 1,
        flexBasis: '46%',
        minWidth: 160,
        ...sombra(op),
      },
      kpiTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
      kpiLabel: {
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.55,
        textTransform: 'uppercase',
        color: op.onVariant,
        flex: 1,
        paddingRight: 8,
      },
      kpiIcon: {
        fontSize: 20,
        padding: 6,
        borderRadius: 8,
        backgroundColor: op.surfaceContainer,
        color: op.primary,
        overflow: 'hidden',
      },
      kpiIconGreen: { backgroundColor: op.secondaryContainer, color: op.onSecondaryContainer },
      kpiIconRed: { backgroundColor: op.errorContainer, color: op.onErrorContainer },
      kpiIconBlue: { backgroundColor: op.surfaceHigh, color: op.tertiary },
      kpiValue: { fontSize: 28, fontWeight: '700', letterSpacing: -0.56, marginTop: 8, color: op.onSurface },
      kpiValueDanger: { color: op.error },
      kpiSmall: { fontSize: 16, fontWeight: '600', color: op.onVariant },
      kpiTrend: { flexDirection: 'row', alignItems: 'center', gap: 6, fontSize: 12, color: op.onVariant, marginTop: 4, flexWrap: 'wrap' },
      pill: {
        fontSize: 11,
        fontWeight: '700',
        borderRadius: 999,
        paddingVertical: 2,
        paddingHorizontal: 8,
        backgroundColor: op.secondaryContainer,
        color: op.onSecondaryContainer,
        overflow: 'hidden',
      },
      pillWarn: { backgroundColor: op.errorContainer, color: op.onErrorContainer },
      pillInfo: { backgroundColor: op.surfaceContainer, color: op.primary },
      bar: { height: 6, borderRadius: 999, backgroundColor: op.surfaceHigh, overflow: 'hidden', marginTop: 8 },
      barFill: { height: '100%', borderRadius: 999, backgroundColor: op.secondary },
      barFillBlue: { backgroundColor: op.primaryContainer },
      barFillRed: { backgroundColor: op.error },
      kpiSub: { flexDirection: 'row', justifyContent: 'space-between', fontSize: 12, color: op.onVariant, marginTop: 4 },
      kpiSubTxt: { fontSize: 12, color: op.onVariant },
    kpiSubStrong: { color: op.onSurface, fontWeight: '700' },

      // — Cards / grids —
      card: { backgroundColor: op.surfaceLowest, borderRadius: 12, padding: 20, gap: 4, ...sombra(op) },
      cardTitle: { fontSize: 20, fontWeight: '700', letterSpacing: -0.2, color: op.onSurface },
      cardSub: { fontSize: 12, color: op.onVariant, marginTop: 2 },
      cardHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12, marginBottom: 14, flexWrap: 'wrap' },
      cardHeadTitulo: { flex: 1, minWidth: 160 },
      cardFoot: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 14,
        paddingTop: 12,
        gap: 8,
        borderTopWidth: 1,
        borderTopColor: op.surfaceLow,
        flexWrap: 'wrap',
      },
      grid: { gap: 20 },
      metrics3: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        backgroundColor: op.surfaceLow,
        borderRadius: 8,
        padding: 12,
        marginBottom: 12,
      },
      metric: { flexGrow: 1, minWidth: 90 },
      metricLabel: { fontSize: 12, color: op.onVariant, flexDirection: 'row', alignItems: 'center', gap: 6 },
      metricDot: { width: 10, height: 10, borderRadius: 5 },
      metricValue: { fontSize: 20, fontWeight: '700', color: op.onSurface },
      seg: { flexDirection: 'row', backgroundColor: op.surfaceLow, borderRadius: 8, padding: 4, gap: 2, alignSelf: 'flex-start' },
      segBtn: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 6, fontSize: 12, fontWeight: '600', color: op.onVariant },
      segBtnActivo: { backgroundColor: op.surfaceLowest, color: op.primary, fontWeight: '700', ...sombra(op) },
      tagMes: {
        fontSize: 11,
        fontWeight: '700',
        backgroundColor: op.surfaceContainer,
        color: op.primary,
        borderRadius: 4,
        paddingVertical: 2,
        paddingHorizontal: 8,
        overflow: 'hidden',
        alignSelf: 'flex-start',
      },
      xlabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.44,
        color: op.onVariant,
        textTransform: 'uppercase',
        paddingTop: 8,
        gap: 4,
      },

      // — Donut / leyenda —
      donutWrap: { flexDirection: 'row', alignItems: 'center', gap: 20, marginVertical: 12 },
      legend: { flex: 1, gap: 10 },
      legendRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', fontSize: 12, fontWeight: '600' },
      legendIzq: { flexDirection: 'row', alignItems: 'center', gap: 8 },
      legendDot: { width: 12, height: 12, borderRadius: 4 },

      // — Incidencias —
      incList: { gap: 10 },
      inc: {
        backgroundColor: op.surfaceLow,
        borderRadius: 8,
        padding: 14,
        gap: 12,
      },
      incMain: { flexDirection: 'row', gap: 12, flex: 1, minWidth: 0 },
      incIcon: { width: 40, height: 40, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
      incIconRed: { backgroundColor: op.errorContainer, color: op.error },
      incIconBlue: { backgroundColor: op.surfaceHigh, color: op.tertiary },
      incIconGrey: { backgroundColor: op.surfaceContainer, color: op.onVariant },
      incTitulo: { fontSize: 14, fontWeight: '700', flexDirection: 'row', gap: 8, flexWrap: 'wrap', alignItems: 'center', color: op.onSurface },
      incTexto: { fontSize: 12, color: op.onVariant, marginTop: 2 },
      incMeta: { flexDirection: 'row', gap: 8, fontSize: 11, color: op.onVariant, marginTop: 6, flexWrap: 'wrap' },
      incMetaCrit: { color: op.error, fontWeight: '600' },
      incAcciones: { gap: 6, minWidth: 140 },
      link: { color: op.primary, fontSize: 12, fontWeight: '600' },
      muted: { fontSize: 12, color: op.onVariant },

      // — Tablas —
      tableWrap: { overflow: 'hidden', borderRadius: 8 },
      th: {
        backgroundColor: op.surfaceLow,
        paddingVertical: 10,
        paddingHorizontal: 12,
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.44,
        textTransform: 'uppercase',
        color: op.onVariant,
        justifyContent: 'center',
      },
      thTxt: { fontSize: 11, fontWeight: '700', letterSpacing: 0.44, textTransform: 'uppercase', color: op.onVariant },
      td: {
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderBottomWidth: 1,
        borderBottomColor: op.surfaceLow,
        justifyContent: 'center',
      },
      tdTxt: { fontSize: 12, color: op.onSurface },
      num: { textAlign: 'right', fontWeight: '600' },
      restCell: { flexDirection: 'row', alignItems: 'center', gap: 10 },
      restIni: {
        width: 32,
        height: 32,
        borderRadius: 8,
        backgroundColor: op.surfaceContainer,
        color: op.primary,
        fontWeight: '700',
        fontSize: 12,
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
      },
      statusPill: {
        alignSelf: 'flex-start',
        paddingVertical: 3,
        paddingHorizontal: 10,
        borderRadius: 999,
        fontSize: 11,
        fontWeight: '700',
        backgroundColor: op.secondaryContainer,
        color: op.onSecondaryContainer,
        overflow: 'hidden',
      },
      statusPillWarn: { backgroundColor: op.surfaceContainer, color: op.onVariant },
      statusPillInfo: { backgroundColor: op.surfaceHigh, color: op.tertiary },
      statusPillDanger: { backgroundColor: op.errorContainer, color: op.onErrorContainer },

      // — Feed —
      feed: { gap: 14 },
      feedCard: { backgroundColor: op.surfaceLow, borderRadius: 12, padding: 14, gap: 8 },
      feedTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
      feedId: { fontSize: 11, fontWeight: '700', color: op.outline },
      feedName: { fontSize: 14, fontWeight: '700', color: op.onSurface },
      feedRest: { fontSize: 12, color: op.primary, fontWeight: '500' },
      feedMeta: { flexDirection: 'row', gap: 8, fontSize: 12, color: op.onVariant, alignItems: 'center', flexWrap: 'wrap' },
      feedFoot: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderTopWidth: 1,
        borderTopColor: op.surfaceHigh,
        paddingTop: 8,
        fontSize: 12,
        color: op.onVariant,
      },
      feedFootStrong: { color: op.secondary, fontWeight: '700' },

      // — Listas —
      list: { gap: 8 },
      listItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
        paddingVertical: 12,
        paddingHorizontal: 14,
        backgroundColor: op.surfaceLow,
        borderRadius: 8,
        alignItems: 'center',
        flexWrap: 'wrap',
      },
      listItemCuerpo: { flex: 1, minWidth: 140 },
      listItemTitulo: { fontSize: 13, fontWeight: '700', color: op.onSurface },
      toolbar: { gap: 8, marginBottom: 12 },
      input: {
        flexGrow: 1,
        minWidth: 160,
        height: 40,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: op.surfaceHigh,
        backgroundColor: op.surfaceLowest,
        color: op.onSurface,
        fontSize: 14,
        paddingHorizontal: 12,
      },
      textarea: { height: 120, paddingTop: 10, textAlignVertical: 'top', fontSize: 14 },
      errorBox: {
        backgroundColor: op.errorContainer,
        color: op.onErrorContainer,
        borderRadius: 8,
        paddingVertical: 10,
        paddingHorizontal: 14,
        fontSize: 13,
        fontWeight: '600',
      },
      successBox: {
        backgroundColor: op.primaryContainer,
        color: '#ffffff',
        borderRadius: 8,
        paddingVertical: 10,
        paddingHorizontal: 14,
        fontSize: 13,
        fontWeight: '600',
      },
      empty: { textAlign: 'center', color: op.onVariant, paddingVertical: 28, paddingHorizontal: 12, fontSize: 13 },
      modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(17,28,45,0.55)',
        padding: 16,
        alignItems: 'center',
        justifyContent: 'center',
      },
      modal: {
        backgroundColor: op.surfaceLowest,
        borderRadius: 12,
        padding: 22,
        width: '100%',
        maxWidth: 520,
        gap: 10,
        ...sombraLg(op),
      },
      modalTitulo: { fontSize: 18, fontWeight: '700', color: op.onSurface },
      field: { gap: 4, marginBottom: 10 },
      fieldLabel: { fontSize: 12, fontWeight: '700', color: op.onVariant },
      modalActions: { flexDirection: 'row', gap: 8, marginTop: 14, flexWrap: 'wrap' },
      code: { fontFamily: MONO, fontSize: 11, backgroundColor: op.surfaceHigh, borderRadius: 4, paddingVertical: 1, paddingHorizontal: 5, color: op.onSurface, overflow: 'hidden' },
      acceso: { backgroundColor: op.surface, padding: 16, gap: 12, flex: 1 },
    }),
  );

  return { s, op };
}
